CC=g++
CFLAGS=-c -Wall
LDFLAGS=-lGL -lGLU -glut
SOURCES=torus.cpp quadrics-surface.cpp
OBJECTS=$(SOURCES:.cpp=.o)
	EXECUTABLE=hello

all: $(SOURCES) $(EXECUTABLE)
		
$(EXECUTABLE): $(OBJECTS) 
		$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
		$(CC) $(CFLAGS) $(LDFLAGS) $< -o $@
